### ISSUE TITLE
Version of package does not match downloaded sources?

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#1]
My installation is using the master-18.09 version of the binaries.

When checking the version of the installed version of the simulation-mars-interfaces package

```
 dpkg -l rock-master-18.09-simulation-mars-interfaces
```

I get

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  rock-master-18.09-simulation-mars-interfaces  0.20180703-1~bionic         amd64                       mars_interfaces

```

If I am right, this means that the installed binaries correspond to the source code as it was on the 3rd of July of 2018 but looking at the source code downloaded in `/opt/rock/master-18.09/include/mars/interfaces/sim`, the versions don't match. For instance, the method `Exists` [pushed on the 20th of April of 2018](https://github.com/rock-simulation/mars/commit/bb0dfe1ec14cd197d8ddd10f5a86f4ed3978f4d6) is not included in the correspondent header.

@2maz

**Comment by 2maz** [comment]
The version string is based on the last commit date. Looking (manually) through the commits and identifying the first one matching 3 July 2018 might be misleading, so please refer to the commit that you can find in the changelog of the package via:

```
$> zless /usr/share/doc/rock-master-18.09-simulation-mars-interfaces/changelog.Debian.gz
```

```
rock-master-18.09-simulation-mars-interfaces (0.20180703-1~bionic) unstable; urgency=low

  * Package automatically built using autoproj-package debian
  * repository: github:/rock-simulation/mars.git
  * branch: refs/heads/master
  * commit: c1824025e6be4320f96637c2155227a41998765e
  * tag: 

 -- Packaging Daemon <rock-dev@dfki.de>  Wed, 26 Sep 2018 00:48:59 +0200

```
