### ISSUE TITLE
logger-proxies not available with master-19.06

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#12]
I am trying to build [rtt_introspection](https://github.com/rock-cpp/rtt_introspection) in a installation that uses the osdeps 19-06. The package requires [logger-proxies](https://github.com/rock-cpp/rtt_introspection/blob/master/src/CMakeLists.txt#L32) from [tools/logger](https://github.com/rock-core/tools-logger).

Installing tools/logger via osdeps no .pc is generated for logger-proxies:
```bash
/opt/rock/master-19.06# find -name logger-proxies.pc
root@ade_dev_cont:/opt/rock/master-19.06# 
```

When building tools/logger from sources (using deb_blacklist) the .pc is correctly generated. 
```bash
/opt/workspace/install# find -name logger-proxies.pc
./lib/pkgconfig/logger-proxies.pc
root@ade_dev_cont:/opt/workspace/install# 
```

The version that the osdeps packages use of tools/logger is up-to-date with the master branch of tools/logger, so my guess is that something is done differently in the build process.

@2maz

**Comment by 2maz** [comment]
Please call apt update and apt upgrade and report back. Issue should be fixed now.

**Comment by Rauldg** [comment]
Checked. It works! Thanks.
