### ISSUE TITLE
20.06 for arm64: missing package list yml

### ISSUE THREAD

**Issue by annaborn** [rock-core/rock-osdeps-package_set#14]
Hello Thomas @2maz ,
I can not use debian 20.06 on arm64. I get the following error message:

ERROR: init.rb(package_set=rock-osdeps):96: Class::release_osdeps_file: rock release 'master-20.06' has no osdeps file for the architecture 'arm64' -- /home/rh5/ROCK/transfit_or_deb/.autoproj/remotes/github__rock_core_rock_osdeps_package_set_git/data/master-20.06-arm64.yml missing

Thank you in advance! :)

**Comment by 2maz** [comment]
master-20.06 has not been officially announced yet since it is undergoing testing - the ongoing beta has support limited to amd64.
See also the support table (branch: test): https://github.com/rock-core/rock-osdeps-package_set/tree/test

**Comment by annaborn** [comment]
@2maz 
Thank you a lot for your reply!

I was hoping to become a tester for arm64 beta release :) 
Since we are currently setting up master 20.06 on our system, we would like to have the same debian release on all components due to communication.

**Comment by 2maz** [comment]
arm64 is available as of now for Debian Buster
