### ISSUE TITLE
In master19.06 drivers/orogen/gps will not install the dependency drivers/orogen/gps_base

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#15]
I noticed that when installing the package `driver/orogen/imu_xsens`, [which depends on `drivers/orogen/gps` ](https://git.hb.dfki.de/dfki-drivers/orogen-imu_xsens/-/blob/master/manifest.xml#L17). The dependency of `drivers/orogen/gps` drivers/gps_base won't be installed using the binaries. A manual `aup drivers/orogen/gps_base` has to be done in order to get the package installed. 

The dependency is currently listed in [`drivers/orogen/gps`](https://github.com/rock-drivers/drivers-orogen-gps/blob/master/manifest.xml#L27) but maybe it wasn't there at the time when the binaries were created or something else.

[Here is a link to the error that gets triggered](http://bob.dfki.uni-bremen.de:8080/job/docker-ade/IMAGE_NO=ubuntu%3A18.04/505/console)

**Comment by 2maz** [comment]
drivers/orogen/gps does not have the dependency to drivers/orogen/gps_base in master-19.06:
see Build-Depends: http://rock.hb.dfki.de/rock-releases/master-19.06/pool/main/r/rock-master-19.06-drivers-orogen-gps/rock-master-19.06-drivers-orogen-gps_0.20170224-1~bionic.dsc

So if you need drivers/orogen/gps_base for other reasons, then you have to add it to your manifest and it will be also installed.

**Comment by Rauldg** [comment]
Yes, indeed. [This commit of drives/orogen/imu_xsens](https://git.hb.dfki.de/dfki-drivers/orogen-imu_xsens/-/commit/de6ef1b474c6d2ca7925d512b4dd2b13fc044ff8) broke compatibility with the debian packages master-19.06.
