### ISSUE TITLE
'rock-create-orogen' is not working with rock-osdeps

### ISSUE THREAD

**Issue by skasperski** [rock-core/rock-osdeps-package_set#21]
Error message is:
```
Package base/templates/cmake_lib is required, but could not be found at /home/rock-user/workspace/master-20.06/base/templates/cmake_lib.
Please make sure you install package base/templates/cmake_lib.
```
The package cmake_lib is installed, but the path where it is searched for seems weird.

**Comment by 2maz** [comment]
Sorry, base-templates-* should not have been part of the distribution.
I removed them from the osdeps files, that should fix the issue.

**Comment by skasperski** [comment]
Works now.
