### ISSUE TITLE
Including Envire Core?

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#5]
Could [Envire Core](https://github.com/envire/envire-envire_core) be included in the next release? I just compiled the library after updating `base/logging` with respect to the packaged version. 

Also the Envire Core dependency [plugin_manager](https://github.com/envire/tools-plugin_manager) would have to be included, it has no problem to build on Ubuntu 18.04.

**Comment by 2maz** [comment]
I will try to get it in.

**Comment by 2maz** [comment]
Just updated master-19.06: should be available for xenial,bionic and stretch (amd64).
Please verify the installation and close issue by reporting on tested platform(s). Thx

**Comment by Rauldg** [comment]
Seems to work!
