### ISSUE TITLE
rock-bundle-sel command not available after install

### ISSUE THREAD

**Issue by Rauldg** [rock-core/rock-osdeps-package_set#9]
After installing `base/scripts` using the debian packages, the command `rock-bundle-sel` is not available.

The command is [defined here](https://github.com/rock-core/base-scripts/blob/master/shell/bash#L4), [here](https://github.com/rock-core/base-scripts/blob/master/shell/sh#L4) and [here](https://github.com/rock-core/base-scripts/blob/master/shell/zsh#L4).

Sourcing one of the files that contain the command (the files get copied in the install) makes the command available

```
source /opt/rock/master-19.06/share/scripts/shell/bash
```

Shouldn't this sourcing command belong to the installation, instead of having to do it manually?

@2maz

**Comment by 2maz** [comment]
It is and the relevant code to start debugging you find here: https://github.com/rock-core/rock-osdeps-package_set/blob/2cc8c48cfa2ec605078f84e498c7789ce244e94e/init.rb#L170

What is the setting of your SHELL variable?

**Comment by Rauldg** [comment]
> What is the setting of your SHELL variable? 

`/bin/bash`

**Comment by Rauldg** [comment]
`/bin/bash` Its not that simple: 

```
# printenv SHELL  #nooutput?
# echo $SHELL
/bin/bash
```

Somehow those two are not the same.

**Comment by Rauldg** [comment]
I have to export the variable. 

```
# export SHELL
# printenv SHELL
/bin/bash
```

Should this export go in the `.env.sh`?  How can it be included there?

**Comment by Rauldg** [comment]
It seems to be a particular feature of my system. I guess it is because I am using a docker container. A walk around is to add this line to the user's `.bashrc`

```
export SHELL
```
